### ISSUE TITLE
`A` moves backwards when cursor is at end of line

### ISSUE THREAD

**Issue by MilesCranmer** [caleb-allen/VimBindings.jl#61]
I have noticed a strange behavior when using the `A` key where, when in normal mode and with the cursor past the end of the line:
```julia
julia> println()█
```
and then hitting `A`, will have the insert mode cursor aligned one back:
```julia
julia> println(|)
```
rather than
```julia
julia> println()|
```
However, when the cursor is anywhere else, such as the second-to-last position:
```julia
julia> println(█
```
or earlier:
```julia
julia> prin█ln()
```
it will successfully move to the end:
```julia
julia> println()|
```

**Comment by caleb-allen** [comment]
Good find, thanks for the detailed examples!

I wonder if the root cause might be similar to #60, where the final character of a line is moved to a newline instead of a newline being appended to the line. In both cases, the "end of line" is off by one. My first guess would be that the issue is caused by `Motions.line_end`

**Comment by caleb-allen** [comment]
Actually it might be the same root cause as #57 as well
