### ISSUE TITLE
Is it possible to remap h,j,k to other keys because of different keyboard layout? 

### ISSUE THREAD

**Issue by benibilme** [caleb-allen/VimBindings.jl#94]
Hello, 

Since there is no discussion section, I had to ask this in this issues section.  Sorry about that. 
I am using non latin1 keyboard. Is it possible to remap vim default keys to something else  such as  `h=>k, j=>k, k=>m`. Of course, I would like to map some other frequently used keys to more appropriate ones according to my keyboad.

Is it possible? If yes, how can I do that?  I have not seen anything in the documentation. 

Thanks in advance.

**Comment by caleb-allen** [comment]
Hey @benibilme, interesting question! And no worries, opening an issue is the right place to ask for this project.

So, my initial thought is that there is not a purpose-built feature in this package to remap keys (although there may  still be a solution to your problem). In the longer term, the direction of this package will be to use `neovim` under the hood, at which point one could configure behavior similarly to vim/neovim.

In terms of solving your issue in the present, though, I don't think it would be too difficult to add a simple configuration option for remapping _some_ of the keys.

You've articulated a few of the mappings you'd like to change, could you describe some of the other frequently used keys you'd like to remap? Is it solely motion commands, or would you also want to be able to remap operators (e.g. `c`, `d`)?

I ask so that I can understand how extensive a "remapping" feature would need to be.

Thanks!

**Comment by Matthieu-Cordonnier** [comment]
Thank you for your reply.
I was indeed thinking of remapping some vim bindings, not the specific REPL keys.

I am hoping for remapping no more than a few motion keys, such as $ or ^, to others keys better suited for a French AZERTY layout.

**Comment by Matthieu-Cordonnier** [comment]
Thank you,
Well my remappings are personal choices and I do not know how standard they are for the AZERTY layout.
As a "starter pack", there are at least 2 motions I would like to remap:

-  ^ -> q  The ^ key is especially inconvenient  because it is a dead key on AZERTY.
-  $ -> ù  

I find these mapping convenient because they (q and ù) are directly accessible on the central row.

For the record, the ù is kind of useless because it is directly accessible on the central row but there is literally only one word from all the french dictionary that uses this letter !
The q is important in vim so I usually remap it to µ, which is also incredibly easily accessible on the central row, and even more useless that the former.

**Comment by caleb-allen** [comment]
@Matthieu-Cordonnier glad to hear!

In that case I'll merge the branch and include the feature in the next package version

**Comment by caleb-allen** [comment]
@Matthieu-Cordonnier this feature is included in `0.5.0` which is now tagged and registered. You may now use the feature with a standard package installation, no need to install a specific branch
